// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZn1y6MFsPNeXRApEX4_IiR1dWmL9dfVY',
    appId: '1:847600666588:web:9e344819e1e0e045ddf119',
    messagingSenderId: '847600666588',
    projectId: 'planning-with-ai-679f3',
    authDomain: 'planning-with-ai-679f3.firebaseapp.com',
    storageBucket: 'planning-with-ai-679f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsHm4VUexf7L37-eXs4BhybfkYlybkZec',
    appId: '1:847600666588:android:3cf1dcebe7881adcddf119',
    messagingSenderId: '847600666588',
    projectId: 'planning-with-ai-679f3',
    storageBucket: 'planning-with-ai-679f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwAuN6Dx-_mNsn_TVaKp5kEDkP1zzktwM',
    appId: '1:847600666588:ios:20bfe0f0234984b4ddf119',
    messagingSenderId: '847600666588',
    projectId: 'planning-with-ai-679f3',
    storageBucket: 'planning-with-ai-679f3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwAuN6Dx-_mNsn_TVaKp5kEDkP1zzktwM',
    appId: '1:847600666588:ios:20bfe0f0234984b4ddf119',
    messagingSenderId: '847600666588',
    projectId: 'planning-with-ai-679f3',
    storageBucket: 'planning-with-ai-679f3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZn1y6MFsPNeXRApEX4_IiR1dWmL9dfVY',
    appId: '1:847600666588:web:fe02ed63657cf3eeddf119',
    messagingSenderId: '847600666588',
    projectId: 'planning-with-ai-679f3',
    authDomain: 'planning-with-ai-679f3.firebaseapp.com',
    storageBucket: 'planning-with-ai-679f3.firebasestorage.app',
  );
}
